Repository department-of-veterans-affairs/veteran-facing-services-tools, pull requests merged in 2019-12, with the labels that each got.

#192 Update 'ui:reviewField' documentation
  packages/documentation/src/pages/forms/about-the-schema-and-uischema-objects.mdx
Labels: accessibility, invalid, vsa

#191 Kelsonic 3725 update sortabletable
  packages/formation-react/package.json
  packages/formation-react/src/components/SortableTable/SortableTable.jsx
  packages/formation-react/src/components/SortableTable/SortableTable.mdx
Labels: enhancement, vsa

#197 Keyboard-e2e proof of concept code
  packages/formation-react/src/components/SortableTable/SortableTable.jsx
  packages/keyboard-e2e/.gitignore
  packages/keyboard-e2e/README.md
  packages/keyboard-e2e/footnotes.md
  packages/keyboard-e2e/nightwatch.conf.js
  packages/keyboard-e2e/nightwatch.json
  packages/keyboard-e2e/package.json
  packages/keyboard-e2e/src/content/content1.html
  packages/keyboard-e2e/src/css/ally.css
  packages/keyboard-e2e/src/css/forms.css
  packages/keyboard-e2e/src/css/layout.css
  packages/keyboard-e2e/src/css/links.css
  packages/keyboard-e2e/src/css/main.css
  packages/keyboard-e2e/src/css/reset.css
  packages/keyboard-e2e/src/index.html
  packages/keyboard-e2e/src/js/index.js
  packages/keyboard-e2e/test/assertions/isActiveElement.js
  packages/keyboard-e2e/test/assertions/isAllyDeepEquals.js
  packages/keyboard-e2e/test/assertions/isAllyDisabledElement.js
  packages/keyboard-e2e/test/assertions/isAllyFocusableCount.js
  packages/keyboard-e2e/test/assertions/isAllyFocusableObject.js
  packages/keyboard-e2e/test/assertions/isAllyTabbableCount.js
  packages/keyboard-e2e/test/assertions/isAllyTabbableObject.js
  packages/keyboard-e2e/test/commands/allyCheckDisabled.js
  packages/keyboard-e2e/test/commands/allyCheckFocusableCount.js
  packages/keyboard-e2e/test/commands/allyCheckTabbableCount.js
  packages/keyboard-e2e/test/commands/allyConfirmFocusableObject.js
  packages/keyboard-e2e/test/commands/allyConfirmTabbableObject.js
  packages/keyboard-e2e/test/commands/allyDeepEquals.js
  packages/keyboard-e2e/test/commands/checkActiveElement.js
  packages/keyboard-e2e/test/commands/evaluateCheckboxes.js
  packages/keyboard-e2e/test/commands/evaluateRadioButtons.js
  packages/keyboard-e2e/test/commands/evaluateRadioButtonsReverse.js
  packages/keyboard-e2e/test/commands/evaluateSelectMenu.js
  packages/keyboard-e2e/test/commands/evaluateTextInput.js
  packages/keyboard-e2e/test/e2e/content-1.e2e.js
  packages/keyboard-e2e/test/e2e/index.e2e.js
  packages/keyboard-e2e/test/globals/index.js
  packages/keyboard-e2e/webpack.config.js
Labels: accessibility, enhancement
