Repository department-of-veterans-affairs/veteran-facing-services-tools, pull requests merged in 2020-09, with the labels that each got.

#388 Kelsonic 11781 telephone error
  packages/formation-react/package.json
  packages/formation-react/src/components/Telephone/Telephone.jsx
  packages/formation-react/src/components/Telephone/Telephone.mdx
  packages/formation-react/src/components/Telephone/Telephone.unit.spec.jsx
Labels: vsa

#391 Update config-options.mdx
  packages/documentation/src/pages/forms/config-options.mdx
Labels: BAH

#437 Update global help desk phone number
  packages/formation-react/package.json
  packages/formation-react/src/components/Telephone/Telephone.jsx
Labels: bug, vsa

#436 Add HEC phone number
  packages/formation-react/package.json
  packages/formation-react/src/components/Telephone/Telephone.jsx
Labels: enhancement, vsa

#386 Add ui:objectViewField docs
  packages/documentation/src/pages/forms/about-the-schema-and-uischema-objects.mdx
  packages/documentation/src/pages/forms/available-features-and-usage-guidelines.mdx
Labels: vsa
