Repository department-of-veterans-affairs/veteran-facing-services-tools, pull requests merged in 2020-10, with the labels that each got.

#451 Style nested abbr in visited links
  packages/formation/package.json
  packages/formation/sass/base/_va.scss
Labels: bug, design

#475 Add dmc phone numbers to contact list
  packages/formation-react/package.json
  packages/formation-react/src/components/Telephone/Telephone.jsx
  packages/formation-react/src/components/Telephone/Telephone.mdx
Labels: enhancement, vsa

#480 15403: Storybook Component - AdditionalInfo
  packages/formation-react/src/components/AdditionalInfo/AdditionalInfo.stories.jsx
Labels: enhancement

#484 15402: Storybook Component - AcceptTermsPrompt
  packages/formation-react/src/components/AcceptTermsPrompt/AcceptTermsPrompt.jsx
  packages/formation-react/src/components/AcceptTermsPrompt/AcceptTermsPrompt.mdx
  packages/formation-react/src/components/AcceptTermsPrompt/AcceptTermsPrompt.stories.jsx
Labels: enhancement

#485 15407: Storybook Component - EmergencyBanner
  packages/formation-react/src/components/EmergencyBanner/EmergencyBanner.stories.jsx
Labels: enhancement

#487 15409: Storybook Component - ErrorableCheckboxGroup
  packages/formation-react/src/components/ErrorableCheckboxGroup/ErrorableCheckboxGroup.stories.jsx
Labels: enhancement

#490 Update va311 number
  packages/formation-react/package.json
  packages/formation-react/src/components/Telephone/Telephone.jsx
  packages/formation-react/src/components/Telephone/Telephone.mdx
  packages/formation-react/src/components/Telephone/Telephone.unit.spec.jsx
Labels: vsa

#491 Fix errorable text input
  packages/formation-react/package.json
  packages/formation-react/src/components/ErrorableTextInput/ErrorableTextInput.jsx
Labels: vsa
