Repository department-of-veterans-affairs/veteran-facing-services-tools, pull requests merged in 2020-05, with the labels that each got.

#249 Fix nav-paginate-number event when clicking a pagination number link
  packages/formation-react/package.json
  packages/formation-react/src/components/Pagination/Pagination.jsx
Labels: vsa

#231 Update screenreader only definitions
  packages/formation/sass/base/_va.scss
  packages/formation/sass/utilities/_visibility.scss
Labels: accessibility

#254 Add overflow visible to pagination for focus styling
  packages/formation/package.json
  packages/formation/sass/modules/_va-pagination.scss
Labels: vsa

#260 Add centralized Telephone component
  packages/formation-react/src/components/Telephone/Telephone.jsx
  packages/formation-react/src/components/Telephone/Telephone.mdx
  packages/formation-react/src/components/Telephone/Telephone.unit.spec.jsx
Labels: accessibility, enhancement
