Repository department-of-veterans-affairs/veteran-facing-services-tools, pull requests merged in 2020-01, with the labels that each got.

#202 bradl3yC 4560 Reset state and wait for teardown complete
  packages/formation-react/package.json
  packages/formation-react/src/components/modal/Modal.jsx
Labels: vsa

#206 Swap a tag to button tag
  packages/formation-react/package.json
  packages/formation-react/src/components/SortableTable/SortableTable.jsx
Labels: accessibility, vsa

#207 Add/modify props for <Breadcrumbs /> and <Pagination />
  packages/formation-react/package.json
  packages/formation-react/src/components/Breadcrumbs/Breadcrumbs.jsx
  packages/formation-react/src/components/Breadcrumbs/Breadcrumbs.mdx
  packages/formation-react/src/components/Breadcrumbs/Breadcrumbs.unit.spec.jsx
  packages/formation-react/src/components/Pagination/Pagination.jsx
  packages/formation-react/src/components/Pagination/Pagination.mdx
Labels: vsa

#198 Adding documentation for CMS a11y checks on preview.
  packages/documentation/src/pages/platform/architecture/cms.mdx
Labels: accessibility
